# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DooRiBon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DooRiBon

  pod 'SwiftLint'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'
  pod 'Then'
  pod 'Moya'
  pod 'Moya/RxSwift'

end
